import React from "react";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Badge, Body } from "../../components/ui";
import { confirmAction, notify } from "../../lib/dialog";
import { LINKS } from "../../lib/links";
import { Entitlement, isSubscribed, useStore } from "../../state/store";
import { colors, font, radius, spacing } from "../../theme";

function planLabel(e: Entitlement): string {
  if (e === "trial") return "Starter — 3-day trial";
  if (e === "weekly") return "Starter — $4.95 / week";
  return "No active plan";
}

function Row({
  label,
  value,
  onPress,
  danger,
}: {
  label: string;
  value?: string;
  onPress?: () => void;
  danger?: boolean;
}) {
  return (
    <Pressable
      onPress={onPress}
      disabled={!onPress}
      style={({ pressed }) => [styles.row, { opacity: pressed && onPress ? 0.7 : 1 }]}
    >
      <Text style={[styles.rowLabel, danger && { color: colors.danger }]}>{label}</Text>
      {value ? <Text style={styles.rowValue}>{value}</Text> : onPress ? <Text style={styles.chevron}>›</Text> : null}
    </Pressable>
  );
}

export function SettingsTab({ onReset }: { onReset: () => void }) {
  const { state, restoreWeekly, reset } = useStore();

  function onRestore() {
    if (isSubscribed(state.entitlement)) {
      notify("Already active", "Your subscription is active on this account.");
      return;
    }
    restoreWeekly();
    notify("Purchases restored", "Your CatLoop subscription is active again.");
  }

  function onDelete() {
    confirmAction(
      "Delete account",
      "This permanently deletes your CatLoop account, your videos, and your data on this device. This cannot be undone.",
      "Delete",
      () => {
        reset();
        onReset();
      },
      true
    );
  }

  return (
    <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
      <View style={styles.section}>
        <View style={styles.planHeader}>
          <Body style={styles.sectionTitle}>Subscription</Body>
          <Badge
            label={isSubscribed(state.entitlement) ? "Active" : "Inactive"}
            tone={isSubscribed(state.entitlement) ? "success" : "warn"}
          />
        </View>
        <View style={styles.card}>
          <Row label="Plan" value={planLabel(state.entitlement)} />
          <View style={styles.sep} />
          <Row label="Video credits" value={`${state.videoCreditsRemaining} left`} />
          <View style={styles.sep} />
          <Row label="Manage subscription" onPress={() => Linking.openURL(LINKS.manageSubscription)} />
          <View style={styles.sep} />
          <Row label="Restore Purchases" onPress={onRestore} />
        </View>
      </View>

      <View style={styles.section}>
        <Body style={styles.sectionTitle}>AI & safety</Body>
        <View style={styles.card}>
          <Row
            label="Report AI output"
            onPress={() =>
              notify(
                "Report from a video",
                "Open any video in Create or Library and tap Report to flag unsafe, incorrect, or harmful AI output."
              )
            }
          />
          <View style={styles.sep} />
          <Row label="How CatLoop uses AI" onPress={() => Linking.openURL(LINKS.support)} />
        </View>
        <Body style={styles.note}>
          All videos are AI-generated by a third-party video model from the photo
          and prompt you provide. Nothing is captured by a real camera.
        </Body>
      </View>

      <View style={styles.section}>
        <Body style={styles.sectionTitle}>Privacy & legal</Body>
        <View style={styles.card}>
          <Row label="Privacy Policy" onPress={() => Linking.openURL(LINKS.privacy)} />
          <View style={styles.sep} />
          <Row label="Terms of Use" onPress={() => Linking.openURL(LINKS.terms)} />
          <View style={styles.sep} />
          <Row label="Support" onPress={() => Linking.openURL(LINKS.support)} />
        </View>
      </View>

      <View style={styles.section}>
        <View style={styles.card}>
          <Row label="Delete account" onPress={onDelete} danger />
        </View>
      </View>

      <Text style={styles.footer}>CatLoop v1.0 · AI Cat Video Maker</Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scroll: { padding: spacing(5), paddingBottom: spacing(10), gap: spacing(5) },
  section: { gap: spacing(2) },
  sectionTitle: { fontFamily: font.semi, color: colors.textDim, fontSize: 13, textTransform: "uppercase", letterSpacing: 0.5 },
  planHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  card: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: spacing(4),
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: spacing(4),
  },
  rowLabel: { fontFamily: font.medium, color: colors.text, fontSize: 15 },
  rowValue: { fontFamily: font.body, color: colors.textDim, fontSize: 14 },
  chevron: { color: colors.textFaint, fontSize: 20 },
  sep: { height: 1, backgroundColor: colors.cardBorder },
  note: { fontSize: 12, color: colors.textFaint, lineHeight: 18 },
  footer: { fontFamily: font.body, color: colors.textFaint, fontSize: 12, textAlign: "center", marginTop: spacing(2) },
});
